### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by AndrewDaPro6969** [cardillan/mindcode#112]
This is not a bug but I cannot find how to make containers full in the schematic. I've checked vanilla too, it leaves all things holding items and liquids as empty. I need help finding how to encode the container to be full once the schematic is placed.

**Comment by cardillan** [comment]
I don't think this is possible. Contents of a container/vault/tank isn't written to/read from a schematics file in Mindustry.

If Mindustry allowed this, it would be a very powerful feature. Even if the materials to fill the vault were taken from your core - so that building the schematics doesn't miraculously give you extra resources - it would still allow you to move resources from the core to anywhere on the map pretty much instantaneously. So I don't think Mindustry itself will ever support this. Perhaps a mod could be made for this, but I'm not sure if it could be somehow integrated to the standard schematics files.
