### ISSUE TITLE
No warning for elseif statement

### ISSUE THREAD

**Issue by limonovthesecond2** [cardillan/mindcode#121]
It’s very easy to enter `elseif` instead of `elsif,` which will lead to a combined result of `if` and `else`.
MindCode:
```
if x == 1
    print("1")
elseif x == 2
    print("2")
end
```

Compiles to:
```
jump 2 notEqual x 1
print "12"
end
```
Without any `elseif` warning

**Comment by cardillan** [comment]
Thanks for reporting this!

This is another manifestation of the problem described here: #120.

In the longer term, I plan to resolve the issue either by making semicolons compulsory, which would lead to reporting a syntax error in such a code, or by generating warnings about unused standalone expressions. This wouldn't be that easy, as the last expression in a code block typically defines value returned by that code block, but I suppose all unused expressions in a block that aren't last could be reported. This problem should then be reported in such a warning.

It will take some time to get to that, though, and the issue seems to be rather unpleasant. What about making `elseif` a new keyword equivalent to `elsif`?

**Comment by limonovthesecond2** [comment]
Adding an equivalent to this keyword would be helpful for those not familiar with Ruby syntax. However it adds more uncertainty when there are several options for such an ordinary operator

**Comment by limonovthesecond2** [comment]
Making the semicolon mandatory seems like a simpler (not easy) and better solution to avoid adding more work in the future. But I have a related to this issue noob question. It is now clear that the parser defines elseif as a variable. But how does adding a semicolon change this behavior?

**Comment by cardillan** [comment]
At this moment, Mindcode parses this code

```
if x == 1
    print("1")
elseif x == 2
    print("2")
end
```

into something like this

```
<if statement, condition = ...>
    <expression: print("1")>
    <expression: elseif>
    <expression: x == 2>
    <expression: print("2")>
<end of if statement>
```

All these expressions are syntactically valid, and since `elseif` and `x == 2` don't do anything (the first is just a value of a variable named `elseif`, the second is a normal expression), they're just omitted from further analysis and not even reported. Something could be done to detect and report these instances, but it is more implementation work than changing the syntax.

Now, if we make a semicolon at the end of expression compulsory, the source code will look like this:

```
if x == 1
    print("1");
elseif x == 2
    print("2");
end
```

Now, `elseif x==2 print("2")` becomes a single expression, and this expression isn't syntactically correct (cannot be mapped to any valid language construct), so the parser will report a syntax error (probably not with a very user-friendly message, but a syntax error nevertheless).

**Comment by cardillan** [comment]
> Adding an equivalent to this keyword would be helpful for those not familiar with Ruby syntax. However it adds more uncertainty when there are several options for such an ordinary operator

This is true.

Alternatively, I could make `elseif` a keyword, but make it forbidden somehow. That way using `elseif` anywhere in the source code should cause a compilation error.

**Comment by limonovthesecond2** [comment]
Sounds interesting. If this is implemented, it would be nice to add `elif` as well.

**Comment by cardillan** [comment]
I've made this change in my development and currently the above code leads to this error message:

```
Syntax error: [@8,27:32='elseif',<10>,3:0] on line 3:0: mismatched input 'elseif' expecting {'else', 'elsif', 'end'}
```

So, pretty good!

I'm on a vacation now; not sure when I'll get to making a new release.
