### ISSUE TITLE
Uninitialized variable after always true while loop

### ISSUE THREAD

**Issue by limonovthesecond2** [cardillan/mindcode#127]
The variables inside always true `while` loops are marked as `uninitialized`.
Example with warning:
```
while true
    i = switch1.enabled
    if i == 1
        break
    end
end
print(i)
```

**Comment by cardillan** [comment]
This is a bug. I'll need to have a look into it.

Actually, there might be two bugs! In the compiled code

```
sensor i switch1 @enabled
jump 3 equal i 1
jump 0 always 0 0
print i
end
```

the [Jump Straightening optimization](https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX-6-OPTIMIZATIONS.markdown#jump-straightening) should merge the two jumps into one, but it didn't happen.

Thanks for reporting the issue!

**Comment by cardillan** [comment]
The warning is emitted because the DFO optimizer doesn't recognize the loop body will always be executed at least once. The initial condition needs to be inspected and when known to be true at the first iteration, the code path skipping the loop body needs to be excluded from analysis.

The do-while loop is known to be executed at least once and therefore isn't affected:

```
do
    i = switch1.enabled
    if i == 1
        break
    end
loop while true
print(i)
```

This could be a work-around for this very specific situation until a fix is available.
