### ISSUE TITLE
Optimizing variables in arguments of built-in functions

### ISSUE THREAD

**Issue by limonovthesecond2** [cardillan/mindcode#154]
There are built-in functions that have **optional** arguments. Unfortunately, when such arguments are omitted, unnecessary temporary variables are created in their place. This makes debugging the program more difficult due to the increased number of _useless_ variables. It would be nice if such variables were replaced with **zero** at least on `advanced optimization`.

Example:
```
found1 = ulocate(building, core, 1, outx, outy, building);
found2 = ulocate(building, core, 1, outx, outy);
found3 = ulocate(building, core, 1, outx);
found4 = ulocate(building, core, 1);
ulocate(building, core, 1, outx, outy, building);
print(found1, found2, found3, found4, building);
```
Compiled result:
```
ulocate building core 1 @copper outx outy found1 building
ulocate building core 1 @copper outx outy found2 __tmp2
ulocate building core 1 @copper outx __tmp4 found3 __tmp5
ulocate building core 1 @copper __tmp7 __tmp8 found4 __tmp9
ulocate building core 1 @copper outx outy __tmp10 building
print found1
print found2
print found3
print found4
print building
```
Desired result:
```
ulocate building core 1 @copper outx outy found1 building
ulocate building core 1 @copper outx outy found2 0
ulocate building core 1 @copper outx 0 found3 0
ulocate building core 1 @copper 0 0 found4 0
ulocate building core 1 @copper outx outy 0 building
print found1
print found2
print found3
print found4
print building
```

**Comment by cardillan** [comment]
You're right, it is better to avoid creating these unnecessary variables. The replace will be done by the Temporary Variables Elimination optimization so that it could be switched off. I don't expect any problems with this, though, Mindustry Logic clearly doesn't mind using zero as an output variable.

I considered using `null` for these unused outputs, but `0` is both shorter and fits better into the "mlog style".

The fix will be in the next release. Until that time, you can use the new `#set sort-variables;`, it makes inspecting them much much easier in the processor.
