### ISSUE TITLE
Feature request: break, next

### ISSUE THREAD

**Issue by cyclotron3k** [cardillan/mindcode#17]
I think it would be useful to have `break` and `next` implemented for loops. (Also, having `loop` implemented would be a bit cleaner than having to do `while true` all the time).

Thanks for your hard work!

**Comment by IotaBread** [comment]
I also think it would be useful.

To save lines, when the `break` is the only statement inside an `if`, it should compile to "jump if", and when there is something before a `break` inside an `if`, it should compile to "jump always" (the line to jump would be the first one after the while ends). Also, instead of the latter (`if contditon; break; end;`), a `break if condition` could be used. The same would go for `next`.

**Comment by cyclotron3k** [comment]
Closing this issue because it has been moved to the wishlist in https://github.com/francois/mindcode/commit/78f7b8bc91663c74bdb1ed4cbbe85d908c5baefb
