### ISSUE TITLE
"@currentAmmoType" not recognized

### ISSUE THREAD

**Issue by 50275** [cardillan/mindcode#187]
you can sensor currentAmmoType in a turret. mindcode doesn't recognize this variable but the code still works fine.

**Comment by cardillan** [comment]
Yeah, the problem is `@currentAmmoType` is new in version 8 and the list of known Mindustry Logic identifiers isn't versioned yet. I extract this data automatically from Mindustry, and I'll update them all at once when version 8 is out.

In the meantime, I'll add `@currentAmmoType` manually into the list. Whoever uses it probably knows what he's doing :)

Mindcode is designed to support unknown mlog identifiers, so it produces only a warning when encountering one it doesn't know. I plan to add an option for registering new, unknown built-in variables, item/liquid types, blocks and so on using compiler directives (so that items provided by mods could be used, for example), but it will take some time.
