### ISSUE TITLE
`do` is actually mandatory on for loops

### ISSUE THREAD

**Issue by 50275** [cardillan/mindcode#191]
from https://github.com/cardillan/mindcode/blob/main/doc/syntax/SYNTAX-3-STATEMENTS.markdown, describing the for loop:
> Loop over a range of values, in an inclusive or exclusive fashion. The .. range operator indicates an inclusive range (the do keyword separating the condition from the loop body is optional):
```
for n in 14 .. 18 do
  println(n);
end;
printflush(message1);
```
This fails to compile if the `do` keyword is removed.

**Comment by cardillan** [comment]
That's a bug in the documentation. `do` was optional, but has since became mandatory.

(There's also a relaxed syntax, backwards compatible for compiling older sources Mindcode where `do` is still optional, but as you're new to Mindcode, you'd be better off using the default - strict - syntax. The support for relaxed syntax will be dropped shortly anyway.)
