### ISSUE TITLE
Problem compiling with if else

### ISSUE THREAD

**Issue by zhraa11** [cardillan/mindcode#193]
mindcode:
DIR1=@thisx;
if DIR1 == 1 then
    Y1 = Y1 + 1;
else
    Y1 = Y1 - 1;
end;
print(Y1);

logic:
set DIR1 @thisx
op sub Y1 Y1 1
jump 4 notEqual DIR1 1
op add Y1 Y1 1
print Y1
end
print "Compiled by Mindcode - github.com/cardillan/mindcode"

compiled with basic optimization
This makes Y1 unchanged when DIR1==1.

**Comment by zhraa11** [comment]
Hope you can let me know when you have fixed it so I can modify my code. I now use 
mindcode:
if DIR1 == 1 then
Y1 = Y1 + 2;
else
Y1 = Y1 - 1;
end;

to circumvent this problem

**Comment by cardillan** [comment]
The problem is with the If expression optimization. Please use `#set if-expression-optimization = off;` at the beginning of your code as a workaround:

```
#set if-expression-optimization = off;
DIR1=@thisx;
if DIR1 == 1 then
    Y1 = Y1 + 1;
else
    Y1 = Y1 - 1;
end;
print(Y1);
```

Compiled code:

```
set DIR1 @thisx
jump 4 notEqual DIR1 1
op add Y1 Y1 1
jump 5 always 0 0
op sub Y1 Y1 1
print Y1
```

This switches off other If expression optimizations as well, but the impact on the final code should be fairly small. This way you can use correct code and only remove the setting once a fix is available. (I'll be working on it today.)

**Comment by zhraa11** [comment]
Thanks for your help.

**Comment by cardillan** [comment]
@zhraa11 The fix has been deployed.
