### ISSUE TITLE
ulocate parameters generated wrongly

### ISSUE THREAD

**Issue by tomforwood** [cardillan/mindcode#39]
the input 
`ulocate(building,core, false, outx, outy,found,myCore)`
generates
`ulocate building core false @copper outx outy __tmp10 found`
I think it should be
`ulocate building core false @copper outx outy found, myCore`

It looks like it has decided to hard code the found parameter of ulocate to a new temporary variable to use it as the result.

If thios is a deliberate descision then perhaps it could be documented in the syntax?

**Comment by francois** [comment]
Hey, thanks for the bug report. I feel like the optimizer is too aggressive. I almost have a feeling I should offer to enable / disable the optimizer from the UI, so that we can better investigate if the bug is genuine or not.

I can’t promise anything, but if you can checkout the code, I’d try to disable the optimizer and see if the problem is still there.

**Comment by cardillan** [comment]
The problem with this code:
```
ulocate(building,core, false, outx, outy,found,myCore)
```
is that the `found` argument corresponds to function return value. Expected syntax for this statement is:
```
found = ulocate(building,core, false, outx, outy, myCore)
```
which generates correct instruction
```
ulocate building core false @copper outx outy found myCore
```

For a complete descriptions of functions and their mappings to ML instructions see [Function reference for Mindustry Logic 7](../blob/main/FUNCTIONS_V7.markdown).
