### ISSUE TITLE
uradar not compiled when outside if statement

### ISSUE THREAD

**Issue by catornot** [cardillan/mindcode#45]
`uradar(enemy,any,any,distance,0,1,e)`
when put ouside if statement isn't compiled gives nothing

**Comment by francois** [comment]
Hi, thanks for all the bug reports. The optimizer is buggy and requires any of the variables declared in `uradar` in order to work correctly. Otherwise, the optimizer will think « Oh, nothing uses `e`, so I can safely delete this line ». In a « real » program, `e` would not be unused and would thus generate the correct code. Since this is a toy program, mindcode-the-compiler will output nothing.

If you can, you could check out the code and disable the optimizer. You can change the call to `generateAndOptimize` into `generateUnoptimized` at https://github.com/francois/mindcode/blob/main/webapp/src/main/java/info/teksol/mindcode/webapp/CompilerFacade.java#L35 <https://github.com/francois/mindcode/blob/main/webapp/src/main/java/info/teksol/mindcode/webapp/CompilerFacade.java#L35>. This will obviously generate slower code, but the code will be exactly as you wrote.

Alternatively, you can disable the dead code eliminator at https://github.com/francois/mindcode/blob/main/compiler/src/main/java/info/teksol/mindcode/mindustry/LogicInstructionGenerator.java#L30 <https://github.com/francois/mindcode/blob/main/compiler/src/main/java/info/teksol/mindcode/mindustry/LogicInstructionGenerator.java#L30>.

Hope that helps

**Comment by catornot** [comment]
I use e to get the x and y position of the enemy
Thx for the explanation.

**Comment by marralesfios** [comment]
@catornot You should use it in an `if` condition anyway, or you risk getting `x` and `y` of `null`.
