### ISSUE TITLE
Custom Functions: Can they just return numbers?

### ISSUE THREAD

**Issue by schittli** [cardillan/mindcode#8]
Good evening

I tried to write a function that takes an object type like `@ground-factory` and then, it searches the linked blocks for this type. If found, it returns the object:

```
// Gets the block which is linked to the Processor
// Example:  linkedBlock = GetLinkedBlock(@ground-factory)
def GetLinkedBlock(type)
    res = null
 	idxN = 0
 	thisBlock = getlink(idxN)
 	while thisBlock != null && res === null
 		if thisBlock.type == type
            res = thisBlock
 		end
 		idxN += 1
 		thisBlock = getlink(idxN)
 	end
    res
end
```
The function returns `1` if a block is found.

Therefore, I guess that Custom Functions can just return numbers. Is that right?

Thanks a lot, kind regards,
Thomas

**Comment by francois** [comment]
Hye, @schittli. Thanks for the heads up. I didn't think about it before, but yes, this is a limitation of the current implementation of functions. Functions use a Memory Cell or Memory Bank to record parameters and return addresses. Since those buildings only store numbers, we unfortunately can't store anything else.

For the specific example you provided, I don't really see any way around it. We can't pass in the type of building, nor can we return the building from within.

There might be a way around this, but it would prevent certain classes of functions from working, namely recursive functions (functions that call themselves, directly or indirectly).

One thing that Mindcode could do though is provide a warning saying "functions can only return numeric values". That would help the developer.

Thanks for your time and suggestion. I'll add that to the roadmap. Cheers!

**Comment by schittli** [comment]
Thank you very much, @francois, for your help!, now it's clear why it was not working :-)
